/**
 * IISNode Server for Next.js
 *
 * This file is used by IISNode to start the Next.js application.
 * It uses the standalone output generated by Next.js build.
 */

const { createServer } = require('http');
const { parse } = require('url');
const next = require('next');
const path = require('path');

// IISNode provides port via process.env.PORT
const port = process.env.PORT || 3000;
const dev = process.env.NODE_ENV !== 'production';

// For standalone build, Next.js files are in .next/standalone
const app = next({
  dev,
  dir: __dirname,
  conf: {
    distDir: '.next'
  }
});

const handle = app.getRequestHandler();

console.log('Starting Next.js application...');
console.log('Environment:', process.env.NODE_ENV);
console.log('Port:', port);
console.log('Directory:', __dirname);

app.prepare().then(() => {
  createServer((req, res) => {
    try {
      const parsedUrl = parse(req.url, true);
      handle(req, res, parsedUrl);
    } catch (err) {
      console.error('Error handling request:', err);
      res.statusCode = 500;
      res.end('Internal Server Error');
    }
  }).listen(port, (err) => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${port}`);
  });
}).catch((err) => {
  console.error('Error starting Next.js:', err);
  process.exit(1);
});

// Handle uncaught errors
process.on('uncaughtException', (err) => {
  console.error('Uncaught exception:', err);
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('Unhandled rejection at:', promise, 'reason:', reason);
});
