/**
 * PM2 Server for Next.js Runtime App
 *
 * This file is used by PM2 to start the Next.js application in production.
 * It uses the standalone output generated by `next build`.
 *
 * PM2 Configuration:
 *   - Managed by ecosystem.config.js
 *   - Port via environment variable PORT (default: 3001)
 *   - Auto-restart on crash
 *   - Logs to logs/runtime-*.log
 */

const { createServer } = require('http');
const { parse } = require('url');
const next = require('next');
const path = require('path');

// PM2 provides port via process.env.PORT
const port = parseInt(process.env.PORT, 10) || 3001;
const dev = process.env.NODE_ENV !== 'production';

// CRITICAL: Inject runtime basePath from environment variable
// This allows changing basePath without rebuilding
const runtimeBasePath = process.env.__NEXT_ROUTER_BASEPATH || '';
if (runtimeBasePath) {
  console.log('[INFO] Runtime basePath:', runtimeBasePath);
} else {
  console.log('[INFO] No runtime basePath set (root deployment)');
}

// Load next.config.js and inject runtime basePath
const nextConfigPath = path.join(__dirname, 'next.config.js');
delete require.cache[nextConfigPath]; // Clear cache
const nextConfig = require(nextConfigPath);

// Initialize Next.js app with runtime basePath
const app = next({
  dev,
  dir: __dirname,
  conf: {
    ...nextConfig,
    distDir: '.next',
    // Override basePath with runtime value if provided
    ...(runtimeBasePath && {
      basePath: runtimeBasePath,
      assetPrefix: runtimeBasePath
    })
  }
});

const handle = app.getRequestHandler();

// Startup logging
console.log('============================================');
console.log('BIZUIT Custom Forms - Runtime App');
console.log('============================================');
console.log('Environment:', process.env.NODE_ENV || 'development');
console.log('Port:', port);
console.log('Directory:', __dirname);
console.log('Timestamp:', new Date().toISOString());
console.log('============================================');

// Prepare and start server
app.prepare().then(() => {
  const server = createServer((req, res) => {
    try {
      const parsedUrl = parse(req.url, true);
      handle(req, res, parsedUrl);
    } catch (err) {
      console.error('[ERROR] Error handling request:', err);
      console.error('[ERROR] URL:', req.url);
      console.error('[ERROR] Method:', req.method);
      res.statusCode = 500;
      res.end('Internal Server Error');
    }
  });

  server.listen(port, '0.0.0.0', (err) => {
    if (err) {
      console.error('[FATAL] Failed to start server:', err);
      process.exit(1);
    }
    console.log(`✓ Server ready on http://localhost:${port}`);
    console.log(`✓ Process ID: ${process.pid}`);
    console.log('============================================');
  });

  // Graceful shutdown
  const gracefulShutdown = () => {
    console.log('\n[INFO] Received shutdown signal, closing server gracefully...');
    server.close(() => {
      console.log('[INFO] Server closed successfully');
      process.exit(0);
    });

    // Force shutdown after 10 seconds
    setTimeout(() => {
      console.error('[WARN] Forcing shutdown after timeout');
      process.exit(1);
    }, 10000);
  };

  process.on('SIGTERM', gracefulShutdown);
  process.on('SIGINT', gracefulShutdown);

}).catch((err) => {
  console.error('[FATAL] Error starting Next.js:', err);
  process.exit(1);
});

// Global error handlers
process.on('uncaughtException', (err) => {
  console.error('[FATAL] Uncaught exception:', err);
  console.error('[FATAL] Stack:', err.stack);
  // PM2 will restart the process
  process.exit(1);
});

process.on('unhandledRejection', (reason, promise) => {
  console.error('[ERROR] Unhandled rejection at:', promise);
  console.error('[ERROR] Reason:', reason);
  // Log but don't exit (PM2 will handle if it becomes critical)
});

// Log memory usage periodically (every 5 minutes)
if (process.env.NODE_ENV === 'production') {
  setInterval(() => {
    const memUsage = process.memoryUsage();
    console.log('[INFO] Memory usage:', {
      rss: `${Math.round(memUsage.rss / 1024 / 1024)} MB`,
      heapUsed: `${Math.round(memUsage.heapUsed / 1024 / 1024)} MB`,
      heapTotal: `${Math.round(memUsage.heapTotal / 1024 / 1024)} MB`
    });
  }, 5 * 60 * 1000); // 5 minutes
}
